//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : book.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef BOOK_H
#define BOOK_H

#include "Commodity.h"
using namespace std;

class book : public Commodity {
private:
	string issue_date;
	string author;
public:
	void set();
	void show_list();
};

#endif  //_BOOK_H
