//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : book.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "book.h"
#include "iomanip"

void book::set() {
	
}

void book::show_list() {
	ifstream read_b;
	string book_data;
    read_b.open("book.txt",ios::in);
    
    cout<<"商品名稱 "<<setw(12)
		<<"商品編號 "<<setw(12)
    	<<"商品數量 "<<setw(12)
    	<<"商品價格 "<<setw(12)
    	<<"發行時間 "<<setw(12)
		<<"作者:     "<<endl;
    
    while(getline(read_b, book_data)) {
    	cout<<book_data;
    	cout<<endl;
    }
    cout<<endl;
    read_b.close();
}


