//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : Commodity.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef COMMODITY_H 
#define COMMODITY_H
#include <string>
#include <iostream>
#include <cstdlib>
#include <fstream>

using namespace std;

class Commodity {
protected:
	string name;
	int id;
	int num;
	int price;
public:
	Commodity();
	void set();		//
	void show_list();
	void increase();
	void decrease();
	void search();
	void get_price();
	void get_num();
};

#endif  //_COMMODITY_H
