//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : Commodity.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "Commodity.h"

Commodity::Commodity() {
	
}

void Commodity::increase() {

}

void Commodity::decrease() {

}

void Commodity::search() {

}

void Commodity::get_price() {

}

void Commodity::get_num() {

}

