//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : Customer.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef CUSTOMER_H
#define CUSTOMER_H

class Customer {
private:
	int money;
	//int purchase_list;
public:
	Customer();
	void display();
	void set_money();
	void buy();
	void show_buy();
	void show_money();
	void reset();
};

#endif  //_CUSTOMER_H
