//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : Customer.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "Customer.h"
#include <iostream>
#include <cstdlib>
using namespace std;

Customer::Customer() {
	money=0;
}

void Customer::display() {
	set_money();
	int num;
    do {
    	cout<<"按編號選擇... 1.購買商品 2.剩餘金額 3.購買清單 4.回上一選單:"; 
    	cin>>num;
    	switch(num) {
    		case 1:	buy();
    			break;
    		case 2: show_money();
				break;
			case 3: show_buy();
				break;
			case 4: 
				system("cls");
				break;
			default: cout<<"再輸入一次!"<<endl;			
    	}
    } while(num!=4);
    
}

void Customer::set_money() {
	cout<<"你有多少錢?"<<endl;
	cin>>money;
}

void Customer::buy() {
	
}

void Customer::show_buy() {
	
}

void Customer::show_money() {
	cout<<"剩餘 $"<<money<<endl;
}

void Customer::reset() {
	
}

