//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : daily_necessities.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "daily_necessities.h"

void daily_necessities::set() {

}

void daily_necessities::show_list() {

}


