//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : drink.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef DRINK_H
#define DRINK_H

#include "Commodity.h"

class drink : public Commodity {
private:
	string date;
	string producer;
public:
	void set();
	void show_list();

};

#endif  //_DRINK_H
