//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : food.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "food.h"

void food::set() {

}

void food::show_list() {
	ifstream read_f;
    read_f.open("food.txt",ios::in);
    
    read_f>>name;
    read_f>>id;
    read_f>>num;
	read_f>>price;
    read_f>>date;
    read_f>>producer;
    read_f>>weight;
    read_f>>calories;
     
    cout<<"1.商品名稱: "<<name<<endl;
    cout<<"2.商品編號: "<<id<<endl;
    cout<<"3.商品數量: "<<num<<endl;
    cout<<"4.商品價格: "<<price<<endl;
    cout<<"5.食用期限: "<<date<<endl;
	cout<<"6.製造商:   "<<producer<<endl;
	cout<<"7.淨重:     "<<weight<<endl;
	cout<<"8.熱量:     "<<calories<<endl;
    
    read_f.close();
}


