//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : food.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef FOOD_H
#define FOOD_H

#include "Commodity.h"

class food : public Commodity {
private:
	string date;
	string producer;
	float weight;
	float calories;
public:
	void set();
	void show_list();
};

#endif  //_FOOD_H
