//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : full_time.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "full_time.h"

full_time::full_time() {
	salary = 30000;
	month = 1;
}

int full_time::show_salary() {
	return show_salary(); 
}

