//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : full_time.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef FULL_TIME_H
#define FULL_TIME_H

#include "Staff.h"

class full_time : public Staff {
private:
	int salary;
	int month;
public:
	full_time();
	int show_salary();
};

#endif  //_FULL_TIME_H
