//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : ice_food.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef ICE_FOOD_H
#define ICE_FOOD_H

#include "food.h"

class ice_food : public food {
private:
	int temperature;
public:
	void set();
	void show_list();
};

#endif  //_ICE_FOOD_H
