//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : ice_food.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "ice_food.h"

void ice_food::set() {

}

void ice_food::show_list() {

}

