//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : micro_food.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "micro_food.h"

void micro_food::set() {

}

void micro_food::show_list() {

}

