//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : micro_food.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef MICRO_FOOD_H
#define MICRO_FOOD_H

#include "food.h"

class micro_food : public food {
private:
	char heat_time;
public:
	void set();
	void show_list();
};

#endif  //_MICRO_FOOD_H
