//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : part_time.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "part_time.h"
part_time::part_time():Staff() {
	wage = 109;
	hour = 3;
}

int part_time::show_salary() {
	return wage*hour;	
}

