//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : part_time.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef PART_TIME_H
#define PART_TIME_H

#include "Staff.h"

class part_time : public Staff {
private:
	int wage;
	int hour;
public:
	part_time();
	int show_salary();
};

#endif  //_PART_TIME_H
