//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : Staff.cpp
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#include "Staff.h"

Staff::Staff() {
	//ifstream initiate_staff;
	//initiate_staff.open("staff.txt");
	
}

void Staff::display() {
	int num;
    do {
    	cout<<"選擇功能: 1.員工打卡時間 2.員工基本資料 3.雇用員工 4. 解雇員工 5. 回上一選單"<<endl;
    	cin>>num;
    	switch(num) {
    		case 1:	service_time();
    			break;
    		case 2: show_staff(); 
				break;
			case 3: hire();
				break;
			case 4: layoff();
				break;
			case 5: 
				break;
			default: cout<<"再輸入一次!"<<endl;			
    	}
    } while(num!=5);
}

void Staff::show_staff() {
    string stringfromstaff;
    ifstream readstaff;
    readstaff.open("staff.txt");
    while(getline(readstaff,stringfromstaff))
    {
         cout<<stringfromstaff<<endl;
    }
    readstaff.close();
}

void Staff::hire() {
	string temp[10];
	ifstream readstaff;
	readstaff.open("staff.txt");
	int i=0;
	while(getline(readstaff, temp[i])) {
		i++;
	}
	
	ofstream increase_staff;
	increase_staff.open("staff.txt");
	cout<<"姓名: ";
	cin>>name;
	cout<<"ID: ";
	cin>>staff_id;
	cout<<"年齡: ";
	cin>>age; 
	
	for(int j=0; j<10; j++) {
		if(temp[j].length()!=0) {
			increase_staff<<setw(10);
			increase_staff<<temp[j]<<endl;
		}
	}
	//改這邊!! 空格問題 
	increase_staff<<name;
	increase_staff<<setw(10)<<staff_id;
	increase_staff<<setw(10)<<age;
	
}

void Staff::layoff() {
	string match_id;
	cout<<"請輸入解雇員工ID: ";
	cin>>match_id;
	
	string temp[10];
	ifstream readstaff;
	readstaff.open("staff.txt");
	int i=0;
	while(getline(readstaff, temp[i])) {
		if((temp[i].find(match_id))>=0 && (temp[i].find(match_id))<100) temp[i]="";
		i++;
	}
	
	ofstream increase_staff;
	increase_staff.open("staff.txt");
	
	for(int j=0; j<10; j++) {
		if(temp[j].length()!=0) {
			increase_staff<<setw(10);
			increase_staff<<temp[j]<<endl;
		}
	}
}

void Staff::service_time() {
	
}

