//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 便利商店系統
//  @ File Name : Staff.h
//  @ Date : 2013/12/16
//  @ Author : 
//
//


#ifndef STAFF_H
#define STAFF_H
#include <string>
#include <iostream>
#include <fstream> 
#include <iomanip>
using namespace std;

class Staff {
private:
	string name;
	int age;
	int staff_id;
	char time;
public:
	Staff();
	void display();
	void show_staff();
	void hire();
	void layoff();
	void service_time();	//not yet
};

#endif  //_STAFF_H
